const columns = [
  { name: 'Name', uid: 'name', sortable: true },
  { name: 'Action', uid: 'action', sortable: true },
  { name: 'Ip Address', uid: 'ip_address', sortable: true },
  { name: 'Status', uid: 'status', sortable: true },
  { name: 'Time', uid: 'time' },
];

const statusOptions = [
  { name: 'Success', uid: 'success', color: 'success' },
  { name: 'Failed', uid: 'failed', color: 'danger' },
];

const activityLogs = [
  {
    action: 'Login',
    ip_address: '192.168.1.1',
    status: 'Success',
    time: '2023-04-28T14:22:30Z',
    id: 1,
    content_type: 'user',
    user: {
      id: 1,
      name: 'Tony Reichert',
      role: 'Administrator',
      team: 'Management',
      status: 'Verified',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      ban: 'Active',
      email: 'tony.reichert@example.com',
    },
  },
  {
    action: 'Failed Login Attempt',
    ip_address: '192.168.1.2',
    status: 'Failed',
    time: '2023-04-28T14:25:10Z',
    id: 2,
    content_type: 'user',
    user: {
      id: 4,
      name: 'William Howard',
      role: 'Data Entry',
      team: 'Marketing',
      status: 'Verified',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      ban: 'Active',
      email: 'william.howard@example.com',
    },
  },
  {
    action: 'Update Guest House',
    ip_address: '192.168.1.3',
    status: 'Success',
    time: '2023-04-28T15:00:00Z',
    id: 3,
    content_type: 'guest-house',
    user: {
      id: 1,
      name: 'Tony Reichert',
      role: 'Administrator',
      team: 'Management',
      status: 'Verified',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      ban: 'Active',
      email: 'tony.reichert@example.com',
    },
  },
  {
    action: 'Logout',
    ip_address: '192.168.1.1',
    status: 'Success',
    time: '2023-04-28T16:18:45Z',
    id: 4,
    content_type: 'user',
    user: {
      id: 3,
      name: 'Jane Fisher',
      role: 'Data Entry',
      team: 'Development',
      status: 'Verified',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      ban: 'Banned',
      email: 'jane.fisher@example.com',
    },
  },
  {
    action: 'deleted attraction',
    ip_address: '192.168.1.4',
    status: 'Success',
    time: '2023-04-28T16:45:20Z',
    id: 5,
    content_type: 'attraction',
    user: {
      id: 2,
      name: 'Zoey Lang',
      role: 'Developer',
      team: 'Development',
      status: 'Not Verified',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      ban: 'Active',
      email: 'zoey.lang@example.com',
    },
  },
];

export { columns, activityLogs, statusOptions };
