const columns = [
  { name: 'name', uid: 'name', sortable: true },
  { name: 'email', uid: 'email' },
  { name: 'status', uid: 'status', sortable: true },
  { name: 'ban', uid: 'ban', sortable: true },
  { name: 'role', uid: 'role', sortable: true },
  { name: 'actions', uid: 'actions' },
];

const statusOptions = [
  { name: 'Verified', uid: 'verified', color: 'success' },
  { name: 'Not Verified', uid: 'unverified', color: 'warning' },
];

const bannedOptions = [
  { name: 'Active', uid: 'active', color: 'success' },
  { name: 'Banned', uid: 'banned', color: 'danger' },
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    role: 'Administrator',
    team: 'Management',
    status: 'Verified',
    age: '29',
    // avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    ban: 'Active',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    role: 'Developer',
    team: 'Development',
    status: 'Not Verified',
    age: '25',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    ban: 'Active',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    role: 'Data Entry',
    team: 'Development',
    status: 'Verified',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    ban: 'Banned',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    role: 'Data Entry',
    team: 'Marketing',
    status: 'Verified',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    ban: 'Active',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    role: 'Support',
    team: 'Sales',
    status: 'Verified',
    age: '24',
    avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
    ban: 'Banned',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    role: 'Administrator',
    team: 'Management',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    ban: 'Active',
    email: 'brian.kim@example.com',
    status: 'Verified',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    role: 'Developer',
    team: 'Design',
    status: 'Not Verified',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29027007d',
    ban: 'Banned',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    role: 'Data Entry',
    team: 'HR',
    status: 'Verified',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e27027008d',
    ban: 'Banned',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    role: 'Data Entry',
    team: 'Finance',
    status: 'Verified',
    age: '33',
    avatar: 'https://i.pravatar.cc/150?img=4',
    ban: 'Banned',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    role: 'Support',
    team: 'Operations',
    status: 'Verified',
    age: '35',
    avatar: 'https://i.pravatar.cc/150?img=5',
    ban: 'Active',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    role: 'Support',
    team: 'Development',
    status: 'Verified',
    age: '22',
    avatar: 'https://i.pravatar.cc/150?img=8',
    ban: 'Active',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    role: 'Support',
    team: 'Product',
    status: 'Not Verified',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=10',
    ban: 'Active',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    role: 'User',
    team: 'Security',
    status: 'Verified',
    age: '37',
    avatar: 'https://i.pravatar.cc/150?img=12',
    ban: 'Active',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    role: 'User',
    team: 'Marketing',
    status: 'Verified',
    age: '30',
    avatar: 'https://i.pravatar.cc/150?img=16',
    ban: 'Active',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    role: 'User',
    team: 'I. Technology',
    status: 'Not Verified',
    age: '31',
    avatar: 'https://i.pravatar.cc/150?img=15',
    ban: 'Active',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    role: 'Developer',
    team: 'Sales',
    status: 'Verified',
    age: '29',
    avatar: 'https://i.pravatar.cc/150?img=20',
    ban: 'Active',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    role: 'Developer',
    team: 'Analysis',
    status: 'Verified',
    age: '28',
    avatar: 'https://i.pravatar.cc/150?img=33',
    ban: 'Active',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    role: 'Administrator',
    team: 'Testing',
    status: 'Verified',
    age: '27',
    avatar: 'https://i.pravatar.cc/150?img=29',
    ban: 'Active',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    role: 'Administrator',
    team: 'Information Technology',
    status: 'Not Verified',
    age: '32',
    avatar: 'https://i.pravatar.cc/150?img=50',
    ban: 'Active',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    role: 'User',
    team: 'Operations',
    status: 'Verified',
    age: '26',
    avatar: 'https://i.pravatar.cc/150?img=45',
    ban: 'Active',
    email: 'mia.robinson@example.com',
  },
];

export { columns, users, statusOptions, bannedOptions };
